### ISSUE TITLE
ZCrypto parsed the Netscape Comment to unknown extensions

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [zmap/zcrypto#221] opened 2020-05-08 17:29 UTC
ZCrypto parsed the Netscape Comment to unknown extensions
[cert-example-ie-cer40.zip](https://github.com/zmap/zcrypto/files/4600575/cert-example-ie-cer40.zip)

**Comment by Lcys** [comment] 2020-08-06 07:24
I ran into the same problem

**Comment by cpu** [comment] 2021-01-25 22:54
It looks like https://github.com/zmap/zcrypto/issues/248 was filed as a duplicate of this. Since that issue has a little bit more information I'm going to close this one. Thanks!

**Closed by cpu** 2021-01-25 22:54 UTC

**Comment by GOODPWDCETCSZ** [comment] 2021-01-26 00:24
@cpu Thanks.
